-- MySQL Script generated by MySQL Workbench
-- Mon May 25 22:11:03 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema schoolconnect
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema schoolconnect
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `schoolconnect` DEFAULT CHARACTER SET utf8 ;
USE `schoolconnect` ;

-- -----------------------------------------------------
-- Table `schoolconnect`.`people`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schoolconnect`.`people` (
  `id` VARCHAR(64) NOT NULL COMMENT 'Globale ID',
  `firstname` TEXT NOT NULL,
  `lastname` TEXT NOT NULL,
  `preferredname` TEXT NULL COMMENT 'Rufname',
  `sex` TINYINT NULL COMMENT '0: undifined\n1: male\n2: female\n3: diverse',
  `title` TEXT NULL,
  `short` VARCHAR(10) NULL COMMENT 'Kürzel (Dieses Taucht von Lehrern in den Stunden- und Vertretungsplänen auf)',
  `email` TEXT NULL,
  `birthdate` DATE NULL,
  `username` VARCHAR(128) NOT NULL COMMENT 'Maximal 32 Zeichen (wie UNIX-Standard)',
  `unix_userid` INT NOT NULL AUTO_INCREMENT COMMENT 'Auto Increment darf erst bei 20000 starten (Ist daher für die ganze Tabelle so)',
  `smb_homedir` TEXT NULL,
  `persistant` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `unix_userid_UNIQUE` (`unix_userid` ASC),
  UNIQUE INDEX `short_UNIQUE` (`short` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 20000;


-- -----------------------------------------------------
-- Table `schoolconnect`.`devprofile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schoolconnect`.`devprofile` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TEXT NULL,
  `comment` TEXT NULL,
  `setup` TEXT NULL,
  `networklockDefault` TINYINT NULL,
  `allowVNC` TINYINT NULL,
  `settings` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schoolconnect`.`hardwaremodel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schoolconnect`.`hardwaremodel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TEXT NULL,
  `manufacturer` TEXT NULL,
  `hardware` TEXT NULL,
  `vtd` TINYINT NULL,
  `uefi` TINYINT NULL,
  `label` TEXT NULL,
  `info` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schoolconnect`.`device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schoolconnect`.`device` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TEXT NULL,
  `comment` TEXT NULL,
  `diskprotection` TINYINT NULL,
  `devprofile_id` INT NOT NULL,
  `registered` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `networklock` TINYINT NULL,
  `people_id` VARCHAR(64) NULL COMMENT 'persönliches Gerät von?',
  `hardwaremodel_id` INT NULL,
  `screenlock` TINYINT NULL,
  `lastknownIPv4` VARCHAR(15) NULL,
  `lastknownIPv6` VARCHAR(39) NULL,
  `requiresLogin` TINYINT NULL COMMENT 'NULL: Nicht von uns bestimmt\n0: Nein\n1: Ja\n2: nur ohne Internet',
  `room` TEXT NULL,
  `teacher` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_device_profile1_idx` (`devprofile_id` ASC),
  INDEX `fk_device_people1_idx` (`people_id` ASC),
  INDEX `fk_device_hardwaremodel1_idx` (`hardwaremodel_id` ASC),
  CONSTRAINT `fk_device_profile1`
    FOREIGN KEY (`devprofile_id`)
    REFERENCES `schoolconnect`.`devprofile` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_device_people1`
    FOREIGN KEY (`people_id`)
    REFERENCES `schoolconnect`.`people` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_device_hardwaremodel1`
    FOREIGN KEY (`hardwaremodel_id`)
    REFERENCES `schoolconnect`.`hardwaremodel` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schoolconnect`.`hardwareidentifier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schoolconnect`.`hardwareidentifier` (
  `address` VARCHAR(45) NOT NULL,
  `type` TINYINT NOT NULL COMMENT '0: MAC-Address',
  `device_id` INT NOT NULL COMMENT 'Macaddress / Firmware-ID /…',
  PRIMARY KEY (`address`, `type`),
  INDEX `fk_macaddress_computer1_idx` (`device_id` ASC),
  CONSTRAINT `fk_macaddress_computer1`
    FOREIGN KEY (`device_id`)
    REFERENCES `schoolconnect`.`device` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schoolconnect`.`devicegroup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schoolconnect`.`devicegroup` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TEXT NULL,
  `info` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schoolconnect`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schoolconnect`.`image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` TEXT NULL COMMENT 'e.g, VHDX\ne.g. UpdateLin',
  `name` TEXT NULL,
  `info` VARCHAR(45) NULL,
  `location` TEXT NULL,
  `installable` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schoolconnect`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schoolconnect`.`task` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `priority` TINYINT NULL,
  `task` TEXT NULL,
  `scheduled` DATETIME NULL,
  `isCustom` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schoolconnect`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schoolconnect`.`groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TEXT NULL,
  `info` TEXT NULL,
  `type` TINYINT NOT NULL DEFAULT 0 COMMENT 'Bestimmt den Typ der Gruppe.\n0: allgemeine Gruppe\n1: Klasse\n…',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `schoolconnect`.`permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schoolconnect`.`permission` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TEXT NULL,
  `info` TEXT NULL,
  `detail` VARCHAR(16) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `detail_UNIQUE` (`detail` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schoolconnect`.`people_has_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schoolconnect`.`people_has_groups` (
  `people_id` VARCHAR(64) NOT NULL,
  `group_id` INT NOT NULL,
  PRIMARY KEY (`people_id`, `group_id`),
  INDEX `fk_people_has_group_group1_idx` (`group_id` ASC),
  INDEX `fk_people_has_group_people1_idx` (`people_id` ASC),
  CONSTRAINT `fk_people_has_group_people1`
    FOREIGN KEY (`people_id`)
    REFERENCES `schoolconnect`.`people` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_people_has_group_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `schoolconnect`.`groups` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schoolconnect`.`groups_has_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schoolconnect`.`groups_has_permission` (
  `group_id` INT NOT NULL,
  `permission_id` INT NOT NULL,
  PRIMARY KEY (`group_id`, `permission_id`),
  INDEX `fk_group_has_permission_permission1_idx` (`permission_id` ASC),
  INDEX `fk_group_has_permission_group1_idx` (`group_id` ASC),
  CONSTRAINT `fk_group_has_permission_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `schoolconnect`.`groups` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_group_has_permission_permission1`
    FOREIGN KEY (`permission_id`)
    REFERENCES `schoolconnect`.`permission` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schoolconnect`.`userpassword`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schoolconnect`.`userpassword` (
  `people_id` VARCHAR(64) NOT NULL,
  `unix_hash` TEXT NOT NULL,
  `smb_hash` TEXT NULL,
  `hint` TEXT NULL,
  `autogen` TINYINT NULL DEFAULT 0,
  `cleartext` TEXT NULL,
  PRIMARY KEY (`people_id`),
  CONSTRAINT `fk_password_people1`
    FOREIGN KEY (`people_id`)
    REFERENCES `schoolconnect`.`people` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schoolconnect`.`devprofile_has_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schoolconnect`.`devprofile_has_groups` (
  `devprofile_id` INT NOT NULL,
  `group_id` INT NOT NULL COMMENT 'Gruppen, die sich an den geräten anmelden dürfen',
  PRIMARY KEY (`devprofile_id`, `group_id`),
  INDEX `fk_profile_has_group_group1_idx` (`group_id` ASC),
  INDEX `fk_profile_has_group_profile1_idx` (`devprofile_id` ASC),
  CONSTRAINT `fk_profile_has_group_profile1`
    FOREIGN KEY (`devprofile_id`)
    REFERENCES `schoolconnect`.`devprofile` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_profile_has_group_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `schoolconnect`.`groups` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schoolconnect`.`device_has_devicegroup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schoolconnect`.`device_has_devicegroup` (
  `device_id` INT NOT NULL,
  `devicegroup_id` INT NOT NULL,
  PRIMARY KEY (`device_id`, `devicegroup_id`),
  INDEX `fk_device_has_devicegroup_devicegroup1_idx` (`devicegroup_id` ASC),
  INDEX `fk_device_has_devicegroup_device1_idx` (`device_id` ASC),
  CONSTRAINT `fk_device_has_devicegroup_device1`
    FOREIGN KEY (`device_id`)
    REFERENCES `schoolconnect`.`device` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_device_has_devicegroup_devicegroup1`
    FOREIGN KEY (`devicegroup_id`)
    REFERENCES `schoolconnect`.`devicegroup` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schoolconnect`.`device_has_task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schoolconnect`.`device_has_task` (
  `device_id` INT NOT NULL,
  `task_id` INT NOT NULL,
  `currentstep` INT NULL,
  PRIMARY KEY (`device_id`, `task_id`),
  INDEX `fk_device_has_task_task1_idx` (`task_id` ASC),
  INDEX `fk_device_has_task_device1_idx` (`device_id` ASC),
  CONSTRAINT `fk_device_has_task_device1`
    FOREIGN KEY (`device_id`)
    REFERENCES `schoolconnect`.`device` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_device_has_task_task1`
    FOREIGN KEY (`task_id`)
    REFERENCES `schoolconnect`.`task` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schoolconnect`.`shares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schoolconnect`.`shares` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TEXT NULL,
  `path` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schoolconnect`.`groups_has_shares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schoolconnect`.`groups_has_shares` (
  `shares_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  `permission` TINYINT NULL COMMENT 'Unix-Permission',
  PRIMARY KEY (`shares_id`, `group_id`),
  INDEX `fk_shares_has_group_group1_idx` (`group_id` ASC),
  INDEX `fk_shares_has_group_shares1_idx` (`shares_id` ASC),
  CONSTRAINT `fk_shares_has_group_shares1`
    FOREIGN KEY (`shares_id`)
    REFERENCES `schoolconnect`.`shares` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_shares_has_group_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `schoolconnect`.`groups` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schoolconnect`.`devicegroup_has_shares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schoolconnect`.`devicegroup_has_shares` (
  `devicegroup_id` INT NOT NULL,
  `shares_id` INT NOT NULL,
  `permission` TINYINT NULL COMMENT 'UNIX-Berechtigung für den Share',
  PRIMARY KEY (`devicegroup_id`, `shares_id`),
  INDEX `fk_devicegroup_has_shares_shares1_idx` (`shares_id` ASC),
  INDEX `fk_devicegroup_has_shares_devicegroup1_idx` (`devicegroup_id` ASC),
  CONSTRAINT `fk_devicegroup_has_shares_devicegroup1`
    FOREIGN KEY (`devicegroup_id`)
    REFERENCES `schoolconnect`.`devicegroup` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_devicegroup_has_shares_shares1`
    FOREIGN KEY (`shares_id`)
    REFERENCES `schoolconnect`.`shares` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schoolconnect`.`localLoginLog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schoolconnect`.`localLoginLog` (
  `people_id` VARCHAR(64) NOT NULL,
  `device_id` INT NOT NULL,
  `timestamp` TIMESTAMP NOT NULL,
  `info` TEXT NOT NULL,
  `type` INT NOT NULL,
  `affected` VARCHAR(64) NULL,
  PRIMARY KEY (`people_id`, `device_id`, `timestamp`),
  INDEX `fk_localLoginLog_device1_idx` (`device_id` ASC),
  INDEX `fk_localLoginLog_people2_idx` (`affected` ASC),
  CONSTRAINT `fk_localLoginLog_people1`
    FOREIGN KEY (`people_id`)
    REFERENCES `schoolconnect`.`people` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_localLoginLog_device1`
    FOREIGN KEY (`device_id`)
    REFERENCES `schoolconnect`.`device` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_localLoginLog_people2`
    FOREIGN KEY (`affected`)
    REFERENCES `schoolconnect`.`people` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schoolconnect`.`drivers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schoolconnect`.`drivers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `file` TEXT NOT NULL,
  `parameters` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schoolconnect`.`hardwaremodel_has_drivers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schoolconnect`.`hardwaremodel_has_drivers` (
  `drivers_id` INT NOT NULL,
  `hardwaremodel_id1` INT NOT NULL,
  PRIMARY KEY (`drivers_id`, `hardwaremodel_id1`),
  INDEX `fk_hardwaremodel_has_drivers_drivers1_idx` (`drivers_id` ASC),
  INDEX `fk_hardwaremodel_has_drivers_hardwaremodel1_idx` (`hardwaremodel_id1` ASC),
  CONSTRAINT `fk_hardwaremodel_has_drivers_drivers1`
    FOREIGN KEY (`drivers_id`)
    REFERENCES `schoolconnect`.`drivers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_hardwaremodel_has_drivers_hardwaremodel1`
    FOREIGN KEY (`hardwaremodel_id1`)
    REFERENCES `schoolconnect`.`hardwaremodel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schoolconnect`.`devprofile_has_shares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schoolconnect`.`devprofile_has_shares` (
  `devprofile_id` INT NOT NULL,
  `shares_id` INT NOT NULL,
  PRIMARY KEY (`devprofile_id`, `shares_id`),
  INDEX `fk_devprofile_has_shares_shares1_idx` (`shares_id` ASC),
  INDEX `fk_devprofile_has_shares_devprofile1_idx` (`devprofile_id` ASC),
  CONSTRAINT `fk_devprofile_has_shares_devprofile1`
    FOREIGN KEY (`devprofile_id`)
    REFERENCES `schoolconnect`.`devprofile` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_devprofile_has_shares_shares1`
    FOREIGN KEY (`shares_id`)
    REFERENCES `schoolconnect`.`shares` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schoolconnect`.`device_has_image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schoolconnect`.`device_has_image` (
  `device_id` INT NOT NULL,
  `image_id` INT NOT NULL,
  PRIMARY KEY (`device_id`, `image_id`),
  INDEX `fk_device_has_image_image1_idx` (`image_id` ASC),
  INDEX `fk_device_has_image_device1_idx` (`device_id` ASC),
  CONSTRAINT `fk_device_has_image_device1`
    FOREIGN KEY (`device_id`)
    REFERENCES `schoolconnect`.`device` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_device_has_image_image1`
    FOREIGN KEY (`image_id`)
    REFERENCES `schoolconnect`.`image` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schoolconnect`.`people_has_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schoolconnect`.`people_has_permission` (
  `people_id` VARCHAR(64) NOT NULL,
  `permission_id` INT NOT NULL,
  PRIMARY KEY (`people_id`, `permission_id`),
  INDEX `fk_people_has_permission_permission1_idx` (`permission_id` ASC),
  INDEX `fk_people_has_permission_people1_idx` (`people_id` ASC),
  CONSTRAINT `fk_people_has_permission_people1`
    FOREIGN KEY (`people_id`)
    REFERENCES `schoolconnect`.`people` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_people_has_permission_permission1`
    FOREIGN KEY (`permission_id`)
    REFERENCES `schoolconnect`.`permission` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
